<a href="https://colab.research.google.com/github/NandhanaRameshkumar/Q-learning/blob/main/Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

class QLearningAgent: # class creation
    def __init__(self, num_states, num_actions, learning_rate=0.1, discount_factor=0.9, epsilon=0.1):# creating a constructor for a class
        self.num_states = num_states
        self.num_actions = num_actions
        self.learning_rate = learning_rate
        self.discount_factor = discount_factor
        self.epsilon = epsilon
        self.q_table = np.zeros((num_states, num_actions))# Creating numpy array for storing q values in table

    def choose_action(self, state): # selects an action
        if np.random.uniform(0, 1) < self.epsilon:
            return np.random.choice(self.num_actions)  # Exploration
        else:
            return np.argmax(self.q_table[state])  # Exploitation

    def update_q_table(self, state, action, reward, next_state): # update the q values
        best_next_action = np.argmax(self.q_table[next_state])
        td_target = reward + self.discount_factor * self.q_table[next_state, best_next_action]
        td_error = td_target - self.q_table[state, action]
        self.q_table[state, action] += self.learning_rate * td_error

# Example usage:
if __name__ == "__main__": # main
    # Define environment
    # Example: Grid world environment
    num_states = 16  # Example: 4x4 grid world
    num_actions = 4  # Example: up, down, left, right

    # Create Q-learning agent
    agent = QLearningAgent(num_states, num_actions)

    # Q-learning
    num_episodes = 1000
    max_steps = 100
    for episode in range(num_episodes):
        state = np.random.randint(0, num_states)  # Start from a random state
        for step in range(max_steps):
            action = agent.choose_action(state)
            next_state = np.random.choice(num_states)  # Transition to a random next state
            reward = np.random.normal(0, 1)  # Example: Reward from a normal distribution
            agent.update_q_table(state, action, reward, next_state)
            state = next_state

    # Print learned Q-values
    print("Learned Q-values:")
    print(agent.q_table)
    print(next_state)


Learned Q-values:
[[ 0.1810089   0.18678651  0.01518705  0.71509699]
 [ 0.08713604 -0.03859681  0.16118307  0.24448167]
 [ 0.83979455 -0.33560994 -0.17688869 -0.22256006]
 [ 0.08635554 -0.21298734 -0.10405171 -0.13272356]
 [-0.05129619 -0.46529288  0.01210843 -0.00455259]
 [-0.08920353 -0.20301238 -0.03509546  0.10448408]
 [-0.32868787 -0.07318781 -0.11406954  0.15414881]
 [ 0.4202393   0.02789978 -0.06801074 -0.03380731]
 [ 0.0909128   0.3207324  -0.34631363 -0.08375554]
 [-0.05594635  0.14014766 -0.17209741 -0.31746499]
 [ 0.32978008 -0.0674569   0.05198254  0.02667061]
 [-0.12227229  0.24600829 -0.38031165 -0.3328942 ]
 [ 0.78052375 -0.20177803  0.04631618 -0.12350052]
 [-0.16932811  0.3893554  -0.26882549  0.07006955]
 [ 0.18826156 -0.29526626  0.04192198 -0.0572808 ]
 [-0.08379133  0.66749963 -0.04932762  0.07023948]]
6
